PetStore/Pages/Admin/Banner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PetStore.Models;
using PetStore.Pages.Common;

namespace PetStore.Pages.Admin
{
    public class BannerModel : PageModel
    {
        private readonly AzureBlobService _blobService;
        public BannerModel(AzureBlobService blobService)
        {
            _blobService = blobService;
        }
        public List<Banner> lsBanner { get; set; } = new List<Banner>();
        public int totalPage = 0;
        private int pageSize = 10;
        public int currentPage = 0;
        public IActionResult OnGet(int? current = 1)
        {
            PetStoreContext context = new PetStoreContext();
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            var banner = context.Banners.OrderBy(s => s.Status).AsQueryable();
            totalPage = banner.Count() / pageSize;
            if (banner.Count() % pageSize != 0) totalPage += 1;

            banner = banner.Skip((current.Value - 1) * pageSize).Take(pageSize);
            currentPage = current.Value;

            lsBanner = banner.ToList();
            return Page();
        }
        public async Task<IActionResult> OnPost(string method, string url, IFormFile img)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            if (method == "create")
            {
                string fileName = Path.GetFileName(img.FileName);
                string pathImg = "";
                using (var stream = img.OpenReadStream())
                {
                    pathImg = await _blobService.UploadImageAsync(stream, fileName);
                }
                Banner banner = new Banner();
                banner.BannerUrl = url;
                banner.BannerImage = pathImg;
                banner.ClickCount = 0;
                banner.CreateAt = DateTime.Now;
                banner.Status = "Active";
                PetStoreContext.Ins.Banners.Add(banner);
                await PetStoreContext.Ins.SaveChangesAsync();
            }
            else if (method == "update")
            {
                int bannerId = int.Parse(Request.Form["bannerId"]);
                Banner banner = PetStoreContext.Ins.Banners.Where(b => b.BannerId == bannerId).FirstOrDefault();
                if(banner != null)
                {
                    banner.BannerUrl = url;
                    if(img != null)
                    {
                        string fileName = Path.GetFileName(img.FileName);
                        string pathImg = "";
                        using (var stream = img.OpenReadStream())
                        {
                            pathImg = await _blobService.UploadImageAsync(stream, fileName);
                        }
                        banner.BannerImage = pathImg;
                    }
                    PetStoreContext.Ins.Banners.Update(banner);
                    await PetStoreContext.Ins.SaveChangesAsync();
                }
            }
            return Redirect("/Admin/Banner");
        }
    }
}

PetStore/Pages/Admin/DeleteImgProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PetStore.Models;

namespace PetStore.Pages.Admin
{
    public class DeleteImgProductModel : PageModel
    {
        public IActionResult OnGet(int? id = 1)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            ProductImage proImg = PetStoreContext.Ins.ProductImages.Where(p => p.ImgId == id).FirstOrDefault();
            int? productId = 1;
            if (proImg != null)
            {
                productId = proImg.ProductId;
                PetStoreContext.Ins.ProductImages.Remove(proImg);
                PetStoreContext.Ins.SaveChanges();
            }
            return Redirect("/Admin/DetailImageProduct?id=" + productId);
        }
    }
}

PetStore/Pages/Admin/DetailImageProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PetStore.Models;

namespace PetStore.Pages.Admin
{
    public class DetailImageProductModel : PageModel
    {
        public List<ProductImage> lsProductIMG { get; set; } = new List<ProductImage>();
        string pathSave = "/tpl/img/";
        public IActionResult OnGet(int? id = 1)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            lsProductIMG = PetStoreContext.Ins.ProductImages.Include(p => p.Product).Where(p => p.ProductId == id).ToList();
            return Page();
        }
        public async Task<IActionResult> OnPost(int? productId, IFormFile productImg, string method)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            if (method == "update")
            {
                var ImgID = Request.Form["productIMGId"];
                ProductImage pro = PetStoreContext.Ins.ProductImages.Where(p => p.ImgId == int.Parse(ImgID)).FirstOrDefault();
                if (pro != null) {
                    var filePath = Path.Combine("wwwroot/tpl/img", productImg.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await productImg.CopyToAsync(stream);
                    }
                    string pathImg = pathSave + productImg.FileName;
                    pro.ImgUrl = pathImg;
                    pro.UpdateAt = DateTime.Now;
                    PetStoreContext.Ins.ProductImages.Update(pro);
                    await PetStoreContext.Ins.SaveChangesAsync();
                }
            }
            else if(method == "create")
            {
                List<ProductImage> productIMG = PetStoreContext.Ins.ProductImages.Where(p => p.ProductId == productId).ToList();
                if (productIMG.Count < 4)
                {
                    ProductImage pro = new ProductImage();
                    var filePath = Path.Combine("wwwroot/tpl/img", productImg.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await productImg.CopyToAsync(stream);
                    }
                    string pathImg = pathSave + productImg.FileName;
                    pro.ImgUrl = pathImg;
                    pro.CreateAt = DateTime.Now;
                    pro.ProductId = productId;
                    pro.Status = "Active";
                    PetStoreContext.Ins.ProductImages.Add(pro);
                    await PetStoreContext.Ins.SaveChangesAsync();
                }
            }

            return Redirect("/Admin/DetailImageProduct?id=" + productId);
        }
    }
}

PetStore/Pages/Admin/OrderAdmin.cshtml.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PetStore.Models;
using System.IO.Pipes;

namespace PetStore.Pages.Admin
{
    public class OrderAdminModel : PageModel
    {
        private readonly PetStoreContext _context;
        public OrderAdminModel(PetStoreContext context)
        {
            _context = context;
        }
        public List<Order> orders { get; set; } = new List<Order>();
        public List<Account> accounts { get; set; } = new List<Account>();
        public List<Infor> infors { get; set; } = new List<Infor>();
        public List<PaymentMethod> paymentMethods { get; set; } = new List<PaymentMethod>();
        public List<StatusOrder> statusOrders { get; set; } = new List<StatusOrder>();
        public List<Address> addresses { get; set; } = new List<Address>();
        public List<OrderViewModel> ordersview { get; set; } = new List<OrderViewModel>();
        public int PAGE_SIZE =10;
        public int TotalPages = 0;
        public int PageNumber =0;
        public string Status { get; set; }
        public string Payment { get; set; }
        public string s { get; set; }
        public IActionResult OnGet(string status, string payment, int? pagenum = 1)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName == "Customer")
            {
                return Redirect("/login");
            }
            GetData(status, payment, pagenum);
            return Page();
        }
        private void GetData(string status, string payment, int? pagenum = 1)
        {
            paymentMethods = _context.PaymentMethods.ToList();
            statusOrders = _context.StatusOrders.ToList();
            var query = from o in _context.Orders
                        join i in _context.Infors on o.AccountId equals i.AccountId
                        join a in _context.Addresses on o.AddressId equals a.AddressId
                        join p in _context.PaymentMethods on o.PaymentMethodId equals p.MethodId
                        join s in _context.StatusOrders on o.StatusId equals s.StatusId
                        join sale in _context.Infors on o.SaleId equals sale.AccountId into saleJoin
                        from sale in saleJoin.DefaultIfEmpty()
                        orderby o.CreateAt ascending
                        select new OrderViewModel
                        {
                            OrderId = o.OrderId,
                            Image = i.Image,
                            Name = a.FullNameCustomer,
                            Status = s.StatusName,
                            CreateAt = o.CreateAt,
                            UpdateAt = o.UpdateAt,
                            Note = o.Note,
                            NoteBySale = o.NoteBySale,
                            ImageSale = sale != null ? sale.Image : null,
                            NameSale = sale != null ? sale.Fullname : "Không có sale",
                            Payment = p.MethodName,
                            Addresses = a.Address1,
                            StatusId = o.StatusId,
                            PaymentId = o.PaymentMethodId,
                        };

            if (!string.IsNullOrEmpty(status) && status != "All" && int.TryParse(status, out int statusId))
            {
                query = query.Where(x => x.StatusId == statusId);
            }
            if (!string.IsNullOrEmpty(payment) && payment != "All" && int.TryParse(payment, out int paymentId))
            {
                query = query.Where(x => x.PaymentId == paymentId);
            }

            Status = status;
            Payment = payment;

            int totalItems = query.Count();
            TotalPages = (int)Math.Ceiling(totalItems / (double)PAGE_SIZE);
            PageNumber = pagenum.Value;
            ordersview = query
                .Skip((pagenum.Value - 1) * PAGE_SIZE)
                .Take(PAGE_SIZE)
                .ToList();
        }

       

        public IActionResult OnPostUpdateStatus(string orderId, string status, string sta, string payment, int? pagenum = 1)
        {   
            GetData(sta,payment, pagenum);
            Order o = _context.Orders.Where(x => x.OrderId == int.Parse(orderId)).FirstOrDefault();
            o.StatusId = int.Parse(status);
            _context.Orders.Update(o);
            _context.SaveChanges();
            return RedirectToPage();
        }

        public IActionResult OnGetExport()
        {
            PetStoreContext context = new PetStoreContext();
            var listItem = context.OrderDetails
                                    .Include(x => x.Order)
                                        .ThenInclude(x => x.Address)
                                    .Include(x => x.Order)
                                        .ThenInclude(x => x.Status)
                                    .Include(x => x.Product)
                                        .ThenInclude(x => x.Shop)
                                    .OrderBy(x => x.Order.CreateAt)
                                    .ToList();
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Danh sách sản phẩm");
                worksheet.Cell(1, 1).Value = "Tên sản phẩm";
                worksheet.Cell(1, 2).Value = "Tên Shop";
                worksheet.Cell(1, 3).Value = "Số lượng";
                worksheet.Cell(1, 4).Value = "Giá";
                worksheet.Cell(1, 5).Value = "Ngày đặt";
                worksheet.Cell(1, 6).Value = "Người nhận";
                worksheet.Cell(1, 7).Value = "Số điện thoại người nhận";
                worksheet.Cell(1, 8).Value = "Địa chỉ";
                worksheet.Cell(1, 9).Value = "trạng thái đơn hàng";


                int row = 2;
                foreach(var item in listItem)
                {
                    worksheet.Cell(row, 1).Value = item.Product.ProductName;
                    worksheet.Cell(row, 2).Value = item.Product.Shop.ShopName;
                    worksheet.Cell(row, 3).Value = item.Quantity;
                    worksheet.Cell(row, 4).Value = item.Total;
                    worksheet.Cell(row, 5).Value = item.Order.CreateAt;
                    worksheet.Cell(row, 6).Value = item.Order.Address.FullNameCustomer;
                    worksheet.Cell(row, 7).Value = item.Order.Address.Phone;
                    worksheet.Cell(row, 8).Value = item.Order.Address.Address1;
                    worksheet.Cell(row, 9).Value = item.Order.Status.StatusName;
                    row++;
                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ExportData.xlsx");
                }

            }
        }

        public class OrderViewModel
        {
            public int OrderId { get; set; }
            public string Image { get; set; }
            public string Name { get; set; }
            public string Status { get; set; }
            public DateTime? CreateAt { get; set; }
            public DateTime? UpdateAt { get; set; }
            public string Note { get; set; }
            public string NoteBySale { get; set; }
            public string ImageSale { get; set; }
            public string NameSale { get; set; }
            public string Payment { get; set; }
            public string Addresses { get; set; }
            public int? StatusId { get; set; }
            public int? PaymentId { get; set; }
        }

    }
}

PetStore/Pages/Admin/OrderDetailManage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PetStore.Models;

namespace PetStore.Pages.Admin
{
    public class OrderDetailManageModel : PageModel
    {   
        private readonly PetStoreContext _context;
        public OrderDetailManageModel(PetStoreContext context)
        {
            _context = context;
        }
        public List<OrderDetail> orderDetails { get;set; }= new List<OrderDetail>();
        
        public int Total { get; set; }  
        public IActionResult OnGet(int? id)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName == "Customer")
            {
                return Redirect("/login");
            }
            orderDetails =_context.OrderDetails.Include(x => x.Product).Where(x => x.OrderId == id).ToList();
            int total = 0;
            foreach (var order in orderDetails)
            {
                total += (int)order.Total;
            }
            Total=total;
            return Page();
        }
    }
}

PetStore/Pages/Admin/deleteProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PetStore.Models;

namespace PetStore.Pages.Admin
{
    public class deleteProductModel : PageModel
    {
        public IActionResult OnGet(int? productId)
        {
            string? roleName = HttpContext.Session.GetString("roleName");
            if (roleName == null || roleName != "Admin")
            {
                return Redirect("/Home");
            }
            List<ProductImage> proIMG = PetStoreContext.Ins.ProductImages.Where(p => p.ProductId == productId).ToList();
            if (proIMG != null)
            {
                foreach (var image in proIMG) {
                    image.Status = "deleted";
                }
                PetStoreContext.Ins.ProductImages.UpdateRange(proIMG);
                PetStoreContext.Ins.SaveChanges();
                Product pro = PetStoreContext.Ins.Products.Where(p => p.ProductId == productId).FirstOrDefault();
                if (pro != null)
                {
                    pro.Status = "deleted";
                    PetStoreContext.Ins.Products.Update(pro);
                    PetStoreContext.Ins.SaveChanges();
                }
            }
            return Redirect("/Admin/Product");
        }
    }
}

PetStore/Pages/Admin/DeleteImgProduct.cshtml
@page "/Admin/Product/Image/Delete"
@model PetStore.Pages.Admin.DeleteImgProductModel
@{
}

PetStore/Pages/Admin/OrderAdmin.cshtml
@page "/Admin/Order"
@model PetStore.Pages.Admin.OrderAdminModel
@{
    Layout = "_LayoutAdmin";
}
<div class="container-fluid">
    <div class="layout-specing">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-4">
                <h5 class="mb-0">Đơn Hàng</h5>
                <nav aria-label="breadcrumb" class="d-inline-block mt-2">
                    <ul class="breadcrumb breadcrumb-muted bg-transparent rounded mb-0 p-0">
                        <li class="breadcrumb-item"><a href="index.html">Admin</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Đơn Hàng</li>
                    </ul>
                </nav>
            </div><!--end col-->

            <div class="col-xl-6 col-lg-6 col-md-8 mt-4 mt-md-0">
                <div class="justify-content-md-end">
                    <form method="get">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-sm-12 col-md-6">
                                <div class="mb-0 d-flex gap-3 align-items-center">
                                    <div class="col-5">
                                        <select class="form-control select2input w-100" name="status">
                                            <option value="All" selected="@(Model.Status == "All")">Tất cả</option>
                                            @foreach (var i in Model.statusOrders)
                                            {
                                                <option value="@i.StatusId" selected="@(Model.Status == i.StatusId.ToString())">@i.StatusName</option>
                                            }
                                        </select>
                                    </div>
                                    <div class="col-7">
                                        <select class="form-control select2input w-100" name="payment">
                                            <option value="All" selected="@(Model.Payment == "All")">Tất cả</option>
                                            @foreach (var i in Model.paymentMethods)
                                            {
                                                <option value="@i.MethodId" selected="@(Model.Payment == i.MethodId.ToString())">@i.MethodName</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div><!--end col-->

                            <div class="col-sm-6 col-md-3 mt-4 mt-sm-0">
                                <div class="d-grid">
                                    <button class="btn btn-primary">Lọc</button>
                                </div>
                            </div><!--end col-->
                            <div class="col-sm-6 col-md-3 mt-4 mt-sm-0">
                                <div class="d-grid">
                                    <a href="/Admin/Order?handler=Export" class="btn btn-success">Xuất Excel</a>
                                </div>
                            </div>
                        </div><!--end row-->
                    </form><!--end form-->


                </div>
            </div><!--end col-->
        </div><!--end row-->

        <div class="row">
            <div class="col-12 mt-4">
                <div class="table-responsive bg-white shadow rounded">
                    <table class="table mb-0 table-center">
                        <thead>
                            <tr>
                                <th class="border-bottom p-3" style="min-width: 180px;">Tên</th>
                                <th class="border-bottom p-3" style="min-width: 150px;">Địa Chỉ</th>
                                <th class="border-bottom p-3" style="min-width:150px;">Phương thức thanh toán</th>
                                <th class="border-bottom p-3" style="min-width:150px;">Ngày tạo</th>
                                <th class="border-bottom p-3" style="min-width: 220px;">Trạng Thái</th>
                                <th class="border-bottom p-3" style="min-width:150px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var i in Model.ordersview)
                            {
                                <tr>

                                    <td class="p-3">
                                        <a href="#" class="text-dark">
                                            <div class="d-flex align-items-center">
                                                <img src="@i.Image" class="avatar avatar-md-sm rounded-circle shadow" alt="">
                                                <span class="ms-2">@i.Name</span>
                                            </div>
                                        </a>
                                    </td>
                                    <td class="p-3">@i.Addresses</td>
                                    <td class="p-3">@i.Payment</td>
                                    <td class="p-3">@i.CreateAt</td>
                                    <td class="p-3">
                                        @i.Status
                                        @if (i.StatusId == 1)
                                        {
                                            <form method="post" asp-page-handler="UpdateStatus">
                                                <input type="hidden" name="orderId" value="@i.OrderId" />
                                                <input type="hidden" name="status" value="3" />
                                                <button type="submit" class="btn btn-warning">Chờ giao hàng</button>
                                            </form>
                                        }
                                        @if (i.StatusId == 3)
                                        {
                                            <form method="post" asp-page-handler="UpdateStatus">
                                                <input type="hidden" name="orderId" value="@i.OrderId" />
                                                <input type="hidden" name="status" value="2" />
                                                <button type="submit" class="btn btn-info">Vận chuyển</button>
                                            </form>
                                        }
                                        @if (i.StatusId == 2)
                                        {
                                            <form method="post" asp-page-handler="UpdateStatus">
                                                <input type="hidden" name="orderId" value="@i.OrderId" />
                                                <input type="hidden" name="status" value="4" />
                                                <button type="submit" class="btn btn-success">Hoàn Thành</button>
                                            </form>
                                        }
                                    </td>
                                    <td class="text-end p-3">
                                        <a href="/Admin/OrderDetail/@i.OrderId" class="btn btn-icon btn-pills btn-soft-primary"><i class="uil uil-eye"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!--end row-->

        <div class="row text-center">
            <!-- PAGINATION START -->
            <div class="col-12 mt-4">
                <div class="d-md-flex align-items-center text-center justify-content-between" style="float:right">
                    @*<span class="text-muted me-3">
                    Showing @((Model.PageNumber - 1) *  + 1) -
                    @(Math.Min((int)ViewData["CurrentPage"] * PAGE_SIZE, (int)ViewData["TotalItems"]))
                    out of @ViewData["TotalItems"]
                    </span>*@
                    <ul class="pagination justify-content-center mb-0 mt-3 mt-sm-0">
                        @for (int i = 1; i <= Model.TotalPages; i++)
                        {
                            <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                                <a class="page-link" href="/Admin/Order?pagenum=@i&status=@(Model.Status ?? "All")&payment=@(Model.Payment ?? "All")">@i</a>
                            </li>
                        }
                    </ul>


                </div>
            </div>
            <!-- PAGINATION END -->
        </div>

    </div>
</div><!--end container-->
<!-- View Appintment Start -->
<div class="modal fade" id="viewappointment" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-bottom p-3">
                <h5 class="modal-title" id="exampleModalLabel1">Appointment Detail</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-3 pt-4">
                <div class="d-flex align-items-center">
                    <img src="../assets/images/client/01.jpg" class="avatar avatar-small rounded-pill" alt="">
                    <h5 class="mb-0 ms-3">Howard Tanner</h5>
                </div>
                <ul class="list-unstyled mb-0 d-md-flex justify-content-between mt-4">
                    <li>
                        <ul class="list-unstyled mb-0">
                            <li class="d-flex">
                                <h6>Age:</h6>
                                <p class="text-muted ms-2">25 year old</p>
                            </li>

                            <li class="d-flex">
                                <h6>Gender:</h6>
                                <p class="text-muted ms-2">Male</p>
                            </li>

                            <li class="d-flex">
                                <h6 class="mb-0">Department:</h6>
                                <p class="text-muted ms-2 mb-0">Cardiology</p>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <ul class="list-unstyled mb-0">
                            <li class="d-flex">
                                <h6>Date:</h6>
                                <p class="text-muted ms-2">20th Dec 2020</p>
                            </li>

                            <li class="d-flex">
                                <h6>Time:</h6>
                                <p class="text-muted ms-2">11:00 AM</p>
                            </li>

                            <li class="d-flex">
                                <h6 class="mb-0">Doctor:</h6>
                                <p class="text-muted ms-2 mb-0">Dr. Calvin Carlo</p>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- View Appintment End -->
<!-- Accept Appointment Start -->
<div class="modal fade" id="acceptappointment" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body py-5">
                <div class="text-center">
                    <div class="icon d-flex align-items-center justify-content-center bg-soft-success rounded-circle mx-auto" style="height: 95px; width:95px;">
                        <i class="uil uil-check-circle h1 mb-0"></i>
                    </div>
                    <div class="mt-4">
                        <h4>Accept Appointment</h4>
                        <p class="para-desc mx-auto text-muted mb-0">Great doctor if you need your family member to get immediate assistance, emergency treatment.</p>
                        <div class="mt-4">
                            <a href="#" class="btn btn-soft-success">Accept</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Accept Appointment End -->
<!-- Cancel Appointment Start -->
<div class="modal fade" id="cancelappointment" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body py-5">
                <div class="text-center">
                    <div class="icon d-flex align-items-center justify-content-center bg-soft-danger rounded-circle mx-auto" style="height: 95px; width:95px;">
                        <i class="uil uil-times-circle h1 mb-0"></i>
                    </div>
                    <div class="mt-4">
                        <h4>Cancel Appointment</h4>
                        <p class="para-desc mx-auto text-muted mb-0">Great doctor if you need your family member to get immediate assistance, emergency treatment.</p>
                        <div class="mt-4">
                            <a href="#" class="btn btn-soft-danger">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PetStore/Pages/Admin/deleteProduct.cshtml
@page "/Admin/Product/Delelte"
@model PetStore.Pages.Admin.deleteProductModel
@{
}