PetStore/Models/ForumType.cs
using System;
using System.Collections.Generic;

namespace PetStore.Models
{
    public partial class ForumType
    {
        public ForumType()
        {
            Forums = new HashSet<Forum>();
        }

        public int TypeId { get; set; }
        public string? TypeName { get; set; }

        public virtual ICollection<Forum> Forums { get; set; }
    }
}

PetStore/Pages/Customer/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PetStore.Pages.Customer
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PetStore/Pages/Customer/Blog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PetStore.Pages.Customer
{
    public class BlogModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PetStore/Pages/Customer/BlogDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PetStore.Pages.Customer
{
    public class BlogDetailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PetStore/Pages/Customer/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PetStore.Models;

namespace PetStore.Pages.Customer
{
    public class CartModel : PageModel
    {
        [BindProperty]
        public int proId { get; set; } = 0;
        [BindProperty]
        public List<ShoppingCart> lsCart { get; set; } = new List<ShoppingCart>();
        [BindProperty]
        public int totalPro { get; set; } = 0;
        public void OnGet()
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            if (acc == null)
            {
                Response.Redirect("/login");
                return;
            }
            var context = new PetStoreContext();
            lsCart = context.ShoppingCarts.Include(p => p.Product)
                .ThenInclude(p => p.Category).Where(c => c.AccountId == acc).ToList();
            if(lsCart == null) Response.Redirect("/Home");
            foreach (var p in lsCart)
            {
                totalPro = totalPro + (int)p.Quantity;
            }

        }
        public JsonResult OnPost(int productId, int quantity)
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            if (!acc.HasValue) {
                return new JsonResult(new { success = false, message = "Vui lòng login trước!" });
            }
            var context = new PetStoreContext();
            try
            {
                if (productId <= 0 || quantity <= 0)
                {
                    return new JsonResult(new { success = false, message = "Dữ liệu không hợp lệ!" });
                }

                Product product = context.Products.Find(productId);
                if (product == null) {
                    return new JsonResult(new { success = false, message = "Không tìm thấy sản phẩm!" });
                }

                if(product.UnitInStock < quantity || product.UnitInStock == null)
                {
                    return new JsonResult(new { success = false, message = "Không đủ sản phẩm trong kho!" });
                }

                ShoppingCart cart = context.ShoppingCarts.Where(c => c.AccountId == acc && c.ProductId == productId).FirstOrDefault();
                if (cart == null) {
                    cart = new ShoppingCart();
                    cart.AccountId = acc;
                    cart.Quantity = quantity;
                    cart.ProductId  = productId;
                    cart.CreateAt = DateTime.Now;
                    context.ShoppingCarts.Add(cart);
                    context.SaveChanges();
                }
                else
                {
                    cart.Quantity += quantity;
                    cart.UpdateAt = DateTime.Now;
                    context.ShoppingCarts.Update(cart);
                    context.SaveChanges();
                }
                return new JsonResult(new { success = true, message = "Thêm vào giỏ hàng thành công!" });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return new JsonResult(new { success = false, message = "Đã xảy ra lỗi trên server." });
            }
        }

        public JsonResult OnPostUpdateQuantity(int[] cartIds, int[] quantities)
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            if (!acc.HasValue)
            {
                return new JsonResult(new { success = false, message = "Vui lòng login trước!" });
            }
            var context = new PetStoreContext();
            try
            {
                for (int i=0; i < cartIds.Length; i++) {
                    ShoppingCart cart = context.ShoppingCarts.Where(c => c.CartId == cartIds[i]).Include(p => p.Product).FirstOrDefault();
                    if(cart != null)
                    {
                        if(quantities[i] <= cart.Product.UnitInStock)
                        {
                            if(cart.Quantity != quantities[i])
                            {
                                if (quantities[i] != 0)
                                {
                                    cart.Quantity = quantities[i];
                                    cart.UpdateAt = DateTime.Now;
                                    context.ShoppingCarts.Update(cart);
                                    context.SaveChanges();
                                }
                                else if (quantities[i] == 0)
                                {
                                    context.ShoppingCarts.Remove(cart);
                                    context.SaveChanges();
                                }
                            
                            }
                        }
                        else
                        {
                            return new JsonResult(new { success = false, message = "Số lượng sản phẩm không đủ!" });
                        }
                        
                    }
                }
                return new JsonResult(new { success = true, message = "thành công!" });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, message = "Đã xảy ra lỗi trên server." });
            }
        }
    }
}

PetStore/Pages/Customer/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PetStore.Models;
using PetStore.Pages.Common;
using System.Text.Json;
using System.IO;
using System;
using System.Net.Mail;
using System.Net.Mime;
using System.Net;

namespace PetStore.Pages.Customer
{
    public class CheckoutModel : PageModel
    {
        [BindProperty]
        public List<ShoppingCart> lsCart { get; set; } = new List<ShoppingCart>();
        [BindProperty]
        public int totalPro { get; set; } = 0;
        [BindProperty]
        public List<PaymentMethod> lspayMethod { get; set; } = new List<PaymentMethod>();
        [BindProperty]
        public List<DiscountCode> lsDiscountCode { get; set; } = new List<DiscountCode>();

        public void OnGet(int? productId = null, int? quantity = null)
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            if (acc == null)
            {
                Response.Redirect("/login");
                return;
            }
            if(productId != null && quantity != null)
            {
                ShoppingCart cart = new ShoppingCart();
                cart.CreateAt = DateTime.Now;
                cart.UpdateAt = DateTime.Now;
                cart.AccountId = acc;
                cart.Quantity = quantity;
                cart.ProductId = productId;
                cart.Product = PetStoreContext.Ins.Products.Where(p => p.ProductId == productId).Include(c => c.Category).FirstOrDefault();
                cart.Account = PetStoreContext.Ins.Accounts.Where(a => a.AccountId == acc).FirstOrDefault();
                lsCart.Add(cart);
            }
            else
            {
                lsCart = PetStoreContext.Ins.ShoppingCarts.Include(p => p.Product)
                .ThenInclude(p => p.Category).Include(a => a.Account).Where(c => c.AccountId == acc).ToList();
            }
            
            if(lsCart == null || lsCart.Count == 0)
            {
                Response.Redirect("/Cart");
                return;
            }
            lspayMethod = PetStoreContext.Ins.PaymentMethods.Where(pm => pm.Status == "active").ToList();
            if(lspayMethod == null) Response.Redirect("/Home");
            foreach (var p in lsCart)
            {
                totalPro = totalPro + (int)p.Quantity;
            }
            lsDiscountCode = getAllDiscount();
        }
        private List<DiscountCode> getAllDiscount()
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            var activeDiscounts = PetStoreContext.Ins.DiscountCodes
                                    .Where(d => d.Status == "Active")
                                    .ToList();
            var userOrders = PetStoreContext.Ins.Orders
                            .Where(o => o.AccountId == acc)
                            .Select(o => o.DiscountId)
                            .ToList();
            var availableDiscounts = activeDiscounts
                                    .Where(d => !userOrders.Contains(d.CodeId))
                                    .ToList();
            return availableDiscounts;
        }
        public async Task<IActionResult> OnPostSubmitOrder(string email, string fullname, string phone, string address, string city, string district, string ward, string note, int payment, List<string> dataPro, string discountCode)
        {
            int? acc = HttpContext.Session.GetInt32("acc");
            if (acc == null)
            {
                return Redirect("/login");
            }
            //get data address by fetch API
            using var client = new HttpClient();
            var responseCity = await client.GetStringAsync("https://provinces.open-api.vn/api/?depth=1");
            var cities = JsonSerializer.Deserialize<List<Province>>(responseCity);
            var selectedCity = cities.FirstOrDefault(p => p.code.ToString() == city);
            string cityName = selectedCity != null ? selectedCity.name : "null";

            var responseDistrict = await client.GetStringAsync("https://provinces.open-api.vn/api/p/" + selectedCity.code + "?depth=2");
            var districtsJson = JsonSerializer.Deserialize<DistrictResponse>(responseDistrict);
            List<District> districts = districtsJson.districts.ToList();
            var selectedDistrict = districts.FirstOrDefault(p => p.code.ToString() == district);
            string districtName = selectedDistrict != null ? selectedDistrict.name : "null";

            var responseWard = await client.GetStringAsync("https://provinces.open-api.vn/api/d/" + selectedDistrict.code + "?depth=2");
            var wardJson = JsonSerializer.Deserialize<WardResponse>(responseWard);
            List<Ward> wards = wardJson.wards.ToList();
            var selectedWards = wards.FirstOrDefault(p => p.code.ToString() == ward);
            string wardName = selectedWards != null ? selectedWards.name : "null";

            string completeAddress = address + ", " + wardName + ", " + districtName + ", " + cityName;

            //insert Address to database
            Address add = new Address();
            try
            {

                add.FullNameCustomer = fullname;
                add.Phone = phone;
                add.Address1 = completeAddress;
                add.Email = email;
                PetStoreContext.Ins.Addresses.Add(add);
                await PetStoreContext.Ins.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            //assign to sale
            Account sale = PetStoreContext.Ins.Accounts.FirstOrDefault(a => a.RoleId == 2);

            //get first status of order
            StatusOrder stt = PetStoreContext.Ins.StatusOrders.First();

            //Get Discount
            lsDiscountCode = getAllDiscount();
            DiscountCode discount = lsDiscountCode.Where(d => d.Code == discountCode).FirstOrDefault();
            List<Order> ordersAccount = PetStoreContext.Ins.Orders.Where(o => o.AccountId == acc).ToList();
            bool isDiscountUsed = true;
            if(ordersAccount != null && discount != null)
            {
                isDiscountUsed = ordersAccount.Any(o => o.DiscountId != null && o.DiscountId == discount.CodeId);
            }
            int? discountPercent = 0;
            if (!isDiscountUsed) { discountPercent = discount.DiscountPercent;}
            Order od = new Order();

            //insert order to database
            try
            {
                if (!isDiscountUsed) od.DiscountId = discount.CodeId;
                od.CreateAt = DateTime.Now;
                od.Note = note;
                od.SaleId = sale == null ? null : sale.AccountId;
                od.AccountId = acc;
                od.AddressId = add.AddressId;
                od.StatusId = stt.StatusId;
                od.PaymentMethodId = payment;
                PetStoreContext.Ins.Orders.Add(od);
                await PetStoreContext.Ins.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return Redirect("/Checkout");
            }

            //insert to order detail
            List<OrderDetail> orderDetails = new List<OrderDetail>();
            try
            {
                foreach (var data in dataPro)
                {
                    int productId = int.Parse(data.Split("-")[0]);
                    int quantity = int.Parse(data.Split("-")[1]);

                    Product pro = PetStoreContext.Ins.Products.Where(p => p.ProductId == productId).FirstOrDefault();
                    if(pro == null) return Redirect("/Home");
                    OrderDetail odd = new OrderDetail
                    {
                        CreateAt = DateTime.Now,
                        Quantity = quantity,
                        ProductId = productId,
                        OrderId = od.OrderId,
                        UnitPrice = pro.Price,
                        Total = (pro.Price - (pro.Price * (decimal)discountPercent / 100)) * quantity
                    };

                    orderDetails.Add(odd);
                }

                PetStoreContext.Ins.OrderDetails.AddRange(orderDetails);
                await PetStoreContext.Ins.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return Redirect("/Checkout");
            }

            //fetch data from cart of customer
            lsCart = PetStoreContext.Ins.ShoppingCarts.Include(p => p.Product)
                    .ThenInclude(p => p.Category).Include(a => a.Account).Where(c => c.AccountId == acc).ToList();

            //delete product in cart if exist
            try
            {
                List<ShoppingCart> cart = new List<ShoppingCart>();
                foreach (var data in dataPro) {
                    int productId = int.Parse(data.Split("-")[0]);
                    int quantity = int.Parse(data.Split("-")[1]);
                    ShoppingCart cartExist = lsCart.Where(c => c.ProductId == productId).FirstOrDefault();
                    //if exist in cart
                    if (cartExist != null) {
                        //delete if quantity is the same or cart is smaller
                        if (cartExist.Quantity <= quantity) {
                            PetStoreContext.Ins.ShoppingCarts.Remove(cartExist);
                            await PetStoreContext.Ins.SaveChangesAsync();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return Redirect("/Checkout");
            }

            //calculate total of order
            int totalPrice = 0;
            foreach (var p in orderDetails)
            {

PetStore/Pages/Customer/ClickBanner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PetStore.Models;

namespace PetStore.Pages.Customer
{
    public class ClickBannerModel : PageModel
    {
        public IActionResult OnGet(int? id = 1)
        {
            Banner banner = PetStoreContext.Ins.Banners.Where(b => b.BannerId == id).FirstOrDefault();
            if(banner != null)
            {
                banner.ClickCount += 1;
                PetStoreContext.Ins.Banners.Update(banner);
                PetStoreContext.Ins.SaveChanges();
                return Redirect(banner.BannerUrl);
            }
            return Redirect("/Home");
        }
    }
}

PetStore/Pages/Customer/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PetStore.Pages.Customer
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PetStore/Pages/Customer/Service.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PetStore.Pages.Customer
{
    public class ServiceModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PetStore/Pages/Customer/About.cshtml
@page "/About"
@model PetStore.Pages.Customer.AboutModel
@{
    Layout = "_Layout";
}
<style>
    #pills-tabContent {
        min-height: 200px;
    }
</style>
<!-- About Start -->
<div class="container-fluid py-5 ">
    <div class="container">
        <div class="row gx-5">
            <div class="col-lg-5 mb-lg-0" style="min-height: 300px;">
                <div class="position-relative h-100">
                    <img class="position-absolute w-100 h-100 rounded" src="https://kienthucbonphuong.com/images/202006/pet-la-gi/pet-la-gi.jpg" style="object-fit: scale-down;">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="border-start border-5 border-primary ps-5 mb-3">
                    <h6 class="text-primary text-uppercase">Giới Thiệu</h6>
                    <h6 class="display-5 text-uppercase mb-0">Giữ cho thú cưng của bạn luôn vui vẻ</h6>
                </div>
                <h5 class="text-body mb-4">FurFriends là diễn đàn dành riêng cho cộng đồng yêu thú cưng, nơi bạn có thể kết nối, chia sẻ kinh nghiệm chăm sóc, tìm hiểu thông tin hữu ích và giao lưu với những người có chung đam mê. Chúng tôi cam kết xây dựng một không gian thân thiện, sôi động, giúp bạn và thú cưng luôn có những khoảnh khắc vui vẻ, ý nghĩa.</h5>
                <div class="bg-light p-4">
                    <ul class="nav nav-pills justify-content-between mb-3" id="pills-tab" role="tablist">
                        <li class="nav-item w-50" role="presentation">
                            <button class="nav-link text-uppercase w-100 active" id="pills-1-tab" data-bs-toggle="pill"
                                    data-bs-target="#pills-1" type="button" role="tab" aria-controls="pills-1"
                                    aria-selected="true">
                                Sứ mệnh
                            </button>
                        </li>
                        <li class="nav-item w-50" role="presentation">
                            <button class="nav-link text-uppercase w-100" id="pills-2-tab" data-bs-toggle="pill"
                                    data-bs-target="#pills-2" type="button" role="tab" aria-controls="pills-2"
                                    aria-selected="false">
                                Tầm nhìn
                            </button>
                        </li>
                    </ul>
                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-1" role="tabpanel" aria-labelledby="pills-1-tab">
                            <p class="mb-0">
                                Sứ mệnh của chúng tôi là kết nối cộng đồng yêu thú cưng, tạo ra một không gian nơi mọi người có thể chia sẻ kinh nghiệm, kiến thức và những khoảnh khắc đáng nhớ cùng thú cưng của mình. Chúng tôi cam kết mang đến một diễn đàn đáng tin cậy, thân thiện và sôi động, giúp nâng cao chất lượng cuộc sống cho cả thú cưng và chủ nhân của chúng, đồng thời thúc đẩy sự gắn kết giữa con người và những người bạn bốn chân đáng yêu.
                            </p>
                        </div>
                        <div class="tab-pane fade" id="pills-2" role="tabpanel" aria-labelledby="pills-2-tab">
                            <p class="mb-0">
                                Chúng tôi hình dung một cộng đồng nơi mọi thú cưng đều nhận được sự quan tâm, yêu thương và chăm sóc tốt nhất. FurFriends hướng tới việc trở thành diễn đàn hàng đầu dành cho những người yêu thú cưng, nơi kết nối những trái tim chung đam mê, chia sẻ kiến thức và lan tỏa những giá trị tích cực trong việc nuôi dạy thú cưng. Chúng tôi mong muốn xây dựng một không gian thân thiện, nơi mỗi người có thể tìm thấy sự hỗ trợ, cảm hứng và niềm vui từ hành trình đồng hành cùng những người bạn bốn chân của mình.

                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

PetStore/Pages/Customer/Cart.cshtml
@page "/Cart"
@model PetStore.Pages.Customer.CartModel
@{
    Layout = "_Layout";
    decimal? total = 0;
}
<link href="~/css/cartStyle.css" rel="stylesheet">
<div class="container mt-3">

    <nav class="mb-4">
        <a href="#" class="text-decoration-none text-dark">Trang chủ</a> /
        <span>Giỏ hàng</span>
    </nav>

    <!-- Main Content -->
    <div class="row">
        <!-- Left Section: Cart Items -->
        <div class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
            <div class="cart-title fs-2 border-bottom border-dark">
                <h2>Giỏ hàng của bạn</h2>
            </div>

            <p class="mt-3 fs-5">Bạn đang có <strong>@(Model.totalPro != null ? Model.totalPro : "0") sản phẩm</strong> trong giỏ hàng</p>

            @if(Model.lsCart != null)
            {
                <form id="cart" method="post" asp-page="Cart" asp-page-handler="UpdateQuantity">
                    @Html.AntiForgeryToken()
                    @foreach(var c in Model.lsCart)
                    {
                        <input type="hidden" value="@c.CartId" name="cartId"/>
                        total += (@c.Quantity * c.Product.Price);
                        <a href="#" class="cart-item border-bottom py-3 d-flex flex-wrap align-items-center">
                            <img src="@c.Product.Image" alt="Product Image" class="bg-light col-4 img-fluid me-3 rounded-15">
                            <div class="flex-grow-1 col-5">
                                <p class="mb-1 fw-bold fs-5 mb-3 text-truncate">@c.Product.ProductName</p>
                                <p class="mb-1 text-dark mb-4">Danh mục: @c.Product.Category.CategoryName</p>

                                <div class="quantity-control d-flex align-items-center mt-3 mt-md-0">
                                    <div>
                                        @using System.Globalization
                                        <p class="fw-bold fs-5 mb-0"><b>@(((int)c.Product.Price).ToString("N0", CultureInfo.InvariantCulture)) VND</b></p>
                                    </div>
                                    <div class="quantity-control d-flex align-items-center mt-3 mt-md-0 ms-auto col-3">
                                        <button type="button" class="decreaseBtn btn btn-outline-dark btn-sm">-</button>
                                        <input oninput="this.value = Math.max(0, this.value)" type="number" name="quantity" class="quantityInput form-control form-control-sm text-center border-dark mx-2" value="@c.Quantity">
                                        <button type="button" class="increaseBtn btn btn-outline-dark btn-sm">+</button>
                                    </div>
                                </div>
                            </div>
                        </a>
                    }
                </form>
            }
            
        </div>
        <div class="col-lg-1"></div>


        <!-- Right Section: Order Info -->
        <div class="col-lg-4 col-md-12 mt-4 mt-md-0 col-sm-12 col-xs-12">
            <div class="mb-3 border-bottom border-dark">
                <h3 class="mb-3">Thông tin đơn hàng</h3>
            </div>

            <div class="d-flex justify-content-between border-bottom border-dark">
                <p class="mb-3">Tổng tiền:</p>
                @using System.Globalization
                <p class="total-price mb-1 fw-bold">@(((int)total).ToString("N0", CultureInfo.InvariantCulture)) VND</p>
            </div>
            <a href="/Checkout" class="btn checkout-btn w-100 mt-4 py-2 rounded-pill">THANH TOÁN</a>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/updateCartScript.js?v=@DateTime.Now.Ticks"></script>

PetStore/Pages/Customer/ClickBanner.cshtml
@page "/goPage"
@model PetStore.Pages.Customer.ClickBannerModel
@{
}

PetStore/Pages/Customer/deleteForum.cshtml
@page "/Forum/{id}/delete"
@model PetStore.Pages.Customer.deleteForumModel
@{
}